spring:
  application:
    name: springjdbc
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/boarddb
    username: board
    password: board1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    org.springframework.jdbc: DEBUG
