name: Generate changelog
on:
  release:
    types: [created, edited]
  pull_request:
    types: [closed]
  workflow_dispatch:  

permissions: 
  contents: write
  pull-requests: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get first tag
      id: get_first_tag
      run: |
        latest_tag="$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' | sort -V | tail -n1)"
        echo "LATEST_TAG=${latest_tag}" >> "$GITHUB_ENV"
        echo "FIRST_TAG=v1.0.0" >> "$GITHUB_ENV"

    - name: Generate changelog
      uses: janheinrichmerker/action-github-changelog-generator@v2.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        futureRelease: ${{ github.event.release.tag_name || env.LATEST_TAG }}
        output: CHANGELOG.md
        sinceTag: ${{ env.FIRST_TAG }}
        excludeTagsRegex: "^v[0-9]$"

    - name: Git Commit and Push
      uses: somaz94/go-git-commit-action@v1
      with:
        repository: ${{ github.repository }}
        branch: main
        commit_message: "Update changelog"
        user_email: "actions@github.com"
        user_name: "GitHub Actions"
        file_pattern: "CHANGELOG.md"
