name: Generate Changelog

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

concurrency:
  group: changelog-${{ github.ref_name }}
  cancel-in-progress: true

env:
  BASE_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     
          ref: ${{ github.event.repository.default_branch }}


      - name: Sync with remote default branch
        run: |
          git fetch origin
          git checkout -B "$BASE_BRANCH" "origin/$BASE_BRANCH"   # 로컬 브랜치를 원격 최신으로 강제로 맞춤

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate CHANGELOG.md
        run: |
          github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project ${{ github.event.repository.name }} \
            --token ${{ secrets.CHANGELOG_GITHUB_TOKEN }} \
            --output CHANGELOG.md

      - name: Auth for push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git

      - name: Commit & Push CHANGELOG
        run: |
          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci]" || echo "No changes to commit"
          git push origin "$BASE_BRANCH"
